name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the pipeline on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20.0.0
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Your Vercel token
        vercel-args: '--prod'  # Use '--prod' for production deployment
        working-directory: .  # Path to your project directory
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}  # Your Vercel organization ID
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}  # Your Vercel project ID
