name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This runs the pipeline when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust this to your project's Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Adjust if your test command is different

    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/todo-app.git
        git push heroku main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Ensure you set this secret in GitHub
