name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change based on your version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Replace this with your test command

    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/<your-app-name>.git
        git push heroku main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
